<div id="<?php echo $this->grid->getId(); ?>" >

    <div class="row container-fluid">
        <div class="panel panel-info nomargin">
            <div class="panel-heading padding2 text-center">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseFilter_<?php echo $this->grid->getId(); ?>" aria-expanded="true" aria-controls="collapseFilter_<?php echo $this->grid->getId(); ?>" >
                    Filtros
                </a>
            </div>
            <div id="collapseFilter_<?php echo $this->grid->getId(); ?>" class="panel-body panel-collapse collapse"  role="tabpanel" aria-labelledby="headingOne">
                <div id="adest">
                    <?php echo $this->partial("zf-metal/datagrid/form/form-filter-ajax", array("grid"=> $this->grid)); ?>
                </div>

            </div>

        </div>
    </div>



    <div >

     
        <table class="table table-bordered <?php echo $this->grid->getTableClass(); ?>">
            <thead>
                <tr>
                    <?php foreach ($this->grid->getColumns() as $column): ?>
                        <?php if (!$column->getHidden()): ?>
                            <th>

                                <?php echo $this->translate((string) $column); ?>

                                <?php if ($column->getType() != "extra" && $column->getType() != "crud"): ?>

                                    <!--SORT-->
                                    <?php if ($this->grid->getSort() && $this->grid->getSort()->getBy() == $column->getName()): ?>
                                        <?php if ($this->grid->getSort()->getDirection() == "DESC"): ?>
                                            <i class="fa fa-sort-asc" onclick="cdiOrder_<?php echo $this->grid->getId(); ?>('<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => "ASC") + $this->routeParams), true); ?>')"></i>
                                        <?php elseif ($this->grid->getSort()->getDirection() == "ASC"): ?>
                                            <i class="fa fa-sort-desc" onclick="cdiOrder_<?php echo $this->grid->getId(); ?>('<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => "DESC") + $this->routeParams), true); ?>')"></i>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <i class="fa fa-sort" onclick="cdiOrder_<?php echo $this->grid->getId(); ?>('<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => "DESC") + $this->routeParams), true); ?>')"></i>
                                    <?php endif; ?>

                                <?php endif; ?>


                            </th>
                        <?php endif; ?>
                    <?php endforeach; ?>

                </tr>
            <thead>


                <?php if (count($this->grid->getRow())): ?>
                    <?php foreach ($this->grid->getRow() as $data): ?>
                        <tr>
                            <?php foreach ($this->grid->getColumns() as $column): ?>
                                <?php if (!$column->getHidden()): ?>
                                    <td class="<?php echo $column->getTdClass() ?>">
                                        <?php echo $column->getHtmlBegin(); ?>

                                        <?php echo $this->GridField($column, $data); ?>

                                        <?php echo $column->getHtmlEnd(); ?>

                                    </td>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
        </table>

    </div>

    <?php
    echo $this->paginationControl($this->grid->getPaginator(), 'Sliding', $this->partialPagination, array("routeParams" => $this->routeParams,
        'route' => $this->route,'gridId' => $this->grid->getId()));
    ?>


    <?php echo $this->GridCrudAjax($this->grid->getId(), $this->url($this->route, array(), array(), true)); ?>
</div>
