<?php
/* @var $searchForm \ZfMetal\Datagrid\Form\MultiSearch */
/* @var $grid \ZfMetal\Datagrid\Grid */
$searchForm = $grid->getFormSearch();
$searchForm->setAttribute('action', 'javascript:' . $grid->get_f_search() . '()');
?>

<?php
/* @var $element \Zend\Form\Element\Text */
$element = $searchForm->get($grid->getMultiSearhKey());
$element->setAttribute('class', 'form-control');

?>
<div class="pull-right">
    <?php echo $this->form()->openTag($searchForm); ?>

    <?php echo $this->formInput($element); ?>

    <?php echo $this->form()->closeTag($searchForm); ?>
</div>