<?php $record = $this->grid->getRecordDetail(); ?>
<div >
    <a class="btn btn-default" onclick="cdiListRecords_<?php echo $this->grid->getId(); ?>()" >
        <?php echo $this->translate('Listar'); ?>
    </a>
       <?php if($this->grid->getOptions()->getCrudConfig()["edit"]["enable"]): ?>
        <i class='btn btn-danger' onclick='cdiEditRecord_<?php echo $this->grid->getId(); ?>(<?php echo $record->getId(); ?>)'><?php echo $this->translate('Editar'); ?></i>
        <?php endif; ?>
</div>

<div >

    <table class="table table-striped table-bordered">
        <?php foreach ((array) $record as $key => $value): ?>
            <tr>
                <th><?php echo $this->translate($key); ?></th>

                <td>
                    <?php if (substr($key, 0, 1) != '_'): ?>
                        <?php if (is_object($value)): ?>
                            <?php if (is_a($value, "DateTime")): ?>
                                <?php echo $value->format("Y-m-d H:i:s"); ?>
                            <?php else: ?> 
                                <?php echo $value; ?>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php echo $value; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

<?php echo $this->GridCrudAjax($this->grid->getId(),$this->url($this->route,array(),array(),true)); ?>
