<?php $this->flashCurrent(); ?>
<div class="row container-fluid">

    <?php
    $form = $this->grid->getCrudForm();
    $form->setAttribute('onsubmit',"submit.disabled=true; return true;");
    $formConfig = $this->grid->getOptions()->getFormConfig();
    ?>

    <?php
    echo $this->renderForm($form, $formConfig->getStyle(), $formConfig->getColumns(), $formConfig->getGroups());
    ?>
</div>

<?php echo $this->GridCrud($this->grid->getId()); ?>