<?php $importFromCsv = $this->grid->getOptions()->getImportConfig()->getImportFromCsv(); ?>

<?php if ($importFromCsv->getEnable()): ?>

    <<?= $importFromCsv->getBtnTag();?> class="<?= $importFromCsv->getBtnClass()?>" data-toggle="modal" id="btnShowModalImport">
    <?= $importFromCsv->getBtnValue()?>
    </<?= $importFromCsv->getBtnTag();?>>

    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="importModal">
        <div class="modal-dialog">

            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="clearfix"></div>
                    <div style="padding: 10px; margin-top: 20px">
                        <a class="btn btn-primary btn-lg" id="descargaEjemplo" onclick="<?php echo $this->grid->get_f_get_import_example(); ?>()">Descargar Ejemplo</a>
                    </div>
                    <div>

                        <?php
                        $form = new \Zend\Form\Form('import');

                        $form->add(array(
                            'name' => 'file',
                            'type' => 'Zend\Form\Element\File',
                            'attributes' => array(
                                'class' => 'btn btn-default',
                                'accept' => "text/csv",
                                'id'=>'fileUpload'
                            ),
                            'options' => array(
                                'label' => 'Archivo',
                            )
                        ));
                        $form->add(array(
                            'name' => 'import',
                            'type' => 'Zend\Form\Element\Submit',
                            'attributes' => array(
                                'value' => "Importar",
                                'class' => 'pull-right btn btn-primary',
                            ),
                            'options' => array(
                                'label' => 'Importar',
                            )
                        ));
                        $form->add(array(
                            'name' => 'cancel',
                            'type' => 'Zend\Form\Element\Button',
                            'attributes' => array(
                                'value' => "Cancelar",
                                'class' => 'pull-right btn btn-default',
                                'id'=>"btnCancel"
                            ),
                            'options' => array(
                                'label' => 'Cancelar',
                            )
                        ));


                        ?>
                        <?php
                        echo $this->renderForm($form);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $("#btnShowModalImport").on("click", function () {
                $("#importModal").modal("show");
            });
            $("#btnCancel").on("click", function () {
                $("#importModal").modal("hide");
            });
        });
    </script>
<?php endif; ?>