<div id="zf-metal-grid-modal-<?php echo $this->grid->getId();?>" class="modal" role="dialog" tabindex="-1"  style="display: none;"> 
<div  class="modal-dialog" role="document"> 
    <div class="modal-content"> 
        <div class="modal-header"> 
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button> 
            <h4 class="modal-title" id="zf-metal-grid-modal-title-<?php echo $this->grid->getId();?>">

            </h4> 
        </div> 
        <div id="zf-metal-grid-modal-content-<?php echo $this->grid->getId();?>" class="modal-body">

        </div> 
    </div> 
</div>
</div>