<?php $record = $this->grid->getRecordDetail(); ?>
<div >
    <div class="col-lg-6">   
        <a class="btn btn-default" href="<?php echo $this->url($this->route, array(), array('query' => $this->routeParams), true); ?>" ><?php echo $this->translate('Listar'); ?></a>
        <?php if ($this->grid->getOptions()->getCrudConfig()->getEdit()->getEnable()): ?>
            <i class='btn btn-danger' onclick='cdiEditRecord_<?php echo $this->grid->getId(); ?>(<?php echo $record->getId(); ?>)'><?php echo $this->translate('Editar'); ?></i>
        <?php endif; ?>
    </div>

</div>
<div >


    <table class="table table-striped table-bordered table-inverse">
        <?php foreach ((array) $record as $key => $value): ?>
            <tr>
                <?php //Si se puede convertir a string, si no es un objeto o si es un datetime ?>
                <?php if (is_callable([$value, '__toString']) || !is_object($value) || is_a($value, "DateTime")): ?>
                    <th><?php echo $this->translate($key); ?></th>

                    <td>
                        <?php if (substr($key, 0, 1) != '_'): ?>
                            <?php if (is_object($value)): ?>
                                <?php if (is_a($value, "DateTime")): ?>
                                    <?php echo $value->format("Y-m-d H:i:s"); ?>
                                <?php elseif (is_callable([$value, '__toString'])): ?> 
                                    <?php echo $value ?>
                                <?php endif; ?>
                            <?php else: ?>
                                <?php echo $value; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>

                <?php endif; ?>

            </tr>
        <?php endforeach; ?>
    </table>
</div>


<?php echo $this->GridCrud($this->grid->getId()); ?>
