
<?php
$form = $this->grid->getFormFilters();
$form->setAttribute('class', 'form-vertical');
$form->prepare();
echo $this->form()->openTag($form);
?>


<?php $multiplo = 2; ?>
<?php $countRow = 2; ?>
<?php foreach ($form as $element) : ?>

    <?php switch ($element->getAttribute('type')): ?>
<?php case "hidden": ?>
            <?php echo $this->formElement($element); ?>
            <?php break; ?>
        <?php
        case "submit" :
        case "button" :
            ?>


            <?php
            break;
        case "select" :
            ?>

            <?php
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getName());
            ?>
            <div class="col-lg-4 col-md-6 col-xs-12" style="height: 65px">
                <?php echo $this->partial('zf-metal/datagrid/form/filter-element-select', array('element' => $element)); ?>
            </div>

            <?php
            break;
        case "checkbox" :
            ?>

            <?php
            // $element->setAttribute('class', 'form-control');
            ?>
            <div class="col-lg-4 col-md-6 col-xs-12" style="height: 65px">
                <?php echo $this->partial('zf-metal/datagrid/form/filter-element-checkbox', array('element' => $element)); ?>
            </div>

            <?php
            break;
        default:
            ?>

            <?php
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getName());
            ?>
            <div class="col-lg-4 col-md-6 col-xs-12" style="height: 65px">
                <?php echo $this->partial('zf-metal/datagrid/form/filter-element', array('element' => $element)); ?>
            </div>

            <?php break; ?>
    <?php endswitch; ?>

<?php endforeach; ?>
<div class="clearfix"></div>
<div>

<?php $element = $form->get('submitbtn'); ?>

                        <?php echo $this->formElement($element); ?>       

<?php $element = $form->get('resetbtn'); ?>

                        <?php echo $this->formElement($element); ?>       

<?php $element = $form->get('resetsubmitbtn'); ?>
           
                        <?php echo $this->formElement($element); ?>       

</div>
<!--Page-->
<?php echo $this->formElement($form->get("page")) ?>
<?php echo $this->form()->closeTag($form); ?>

<script type="text/javascript">
    function changeOp(element, value) {
        $('[name="' + element + '"]').val(value);
    }

    function resetFormFilter_<?php echo $form->getName(); ?>(sub = false) {
        $(':input', '#<?php echo $form->getName(); ?>')
                .not(':button, :submit, :reset, :hidden')
                .val('')
                .removeAttr('checked')
                .removeAttr('selected');

        if (sub === true) {
            $('#<?php echo $form->getName(); ?>').submit();
        }

    }

</script>
